#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:${GOOGLE_OAUTH_CLIENT_ID}
#            client-secret:${GOOGLE_OAUTH_CLIENT_SECRET}
#
#server:
#  port: 8080